### ISSUE TITLE
Build fails when header file contains parallel accumulator

### ISSUE THREAD

**Issue by luke-a-rogers** [mlysy/RcppTMBTest#3]
Hi Martin,

I'm enjoying using your `TMBtools` package! I noticed that my model failed to compile when I added a parallel accumulator (https://kaskr.github.io/adcomp/structparallel__accumulator.html). Is this expected behaviour? I've included a reprex below:

1. I saved `test_parallel_accumulator.hpp` to `minTMB/src/TMB/`
2. I ran `TMBtools::export_models()`
3. I used `Ctrl/Cmd + Shift + B` to build my package in rstudio

I received the error:

```
In file included from minTMB_TMBExports.cpp:19:
./test_parallel_accumulator.hpp:11:33: error: invalid use of 'this' outside of a non-static member function
        parallel_accumulator<Type> res(this);
                                       ^
./test_parallel_accumulator.hpp:11:29: error: no matching constructor for initialization of 'parallel_accumulator<CppAD::AD<double> >'
        parallel_accumulator<Type> res(this);
                                   ^
minTMB_TMBExports.cpp:53:12: note: in instantiation of function template specialization 'test_parallel_accumulator<CppAD::AD<double> >' requested here
    return test_parallel_accumulator(this);
```

4. I then replaced `parallel_accumulator<Type> res(this);` by `Type res = 0;`
5. I repeated steps 1-3 and the package built without error.
6. I then ran `TMB::runExample(all=TRUE)` to confirm that the `linreg_parallel` example ran successfully on my machine (https://kaskr.github.io/adcomp/linreg_parallel_8cpp-example.html).

My `test_parallel_accumulator.hpp` header file contained:

```
#undef TMB_OBJECTIVE_PTR
#define TMB_OBJECTIVE_PTR obj

template <class Type>
Type test_parallel_accumulator(objective_function<Type>* obj) {
	// Data
	DATA_SCALAR(x);
	// Parameters
	PARAMETER(y);
	// Initialize parallel res to 0
	parallel_accumulator<Type> res(this);
	// Type res = 0;
	// Return the res
	return res;
}

#undef TMB_OBJECTIVE_PTR
#define TMB_OBJECTIVE_PTR this
```

**Comment by mlysy** [comment]
@luke-a-rogers my sincere apologies for the very slow response.  Does it work if you change `this` to `obj` in `parallel_accumulator<Type> res(this);`?

**Comment by kenkellner** [comment]
I also had this error and can confirm that changing `this` to `obj` fixed it. Thank you!

**Comment by mlysy** [comment]
@kenkellner excellent, thanks!
