### ISSUE TITLE
Quick Question About Header Files

### ISSUE THREAD

**Issue by jmhatch** [mlysy/RcppTMBTest#5]
I'm really enjoying using this package! It certainly makes including TMB models in an R package more accessible to the R user community, thanks!

I had a quick question, not an issue. I was poking around the GitHub repo and noticed in the header section of some of the .hpp files in `TMBtools/src/TMB/` there was a number after the `#define` statement and was curious as to why?

For example,
```c++
#define Rxz_dpd_hpp 1
```
versus
```c++
#define NormalNLL_hpp
```
Again, really appreciate this package!

**Comment by mlysy** [comment]
This is a C question which has nothing to do with **TMBtools**, but for which you can find the answer [here](https://stackoverflow.com/questions/60715461/define-vs-define-1).
