### ISSUE TITLE
How to include namespaces?

### ISSUE THREAD

**Issue by jmhatch** [mlysy/RcppTMBTest#7]
`TMBtools` is great, thanks for developing!

I had a question on how to include namespaces when compiling TMB models in R packages using `TMBtools`. For example, I need to use the MVNORM_t function in the `density` namespace. I usually just include the following in the TMB model `using namespace density`, which compiles fine with `TMB`. But I'm having issues doing this while developing an R package currently with `TMBtools`. 

For example, when I run `pkgbuild::compile_dll()` it takes a long time and finishes with `DONE` (no obvious errors). But I also get the following warnings,

`Warning message:
     In file.copy(from = paste0(tmb_name, .Platform$dynlib.ext), to = "..",  : problem copying .\testR_TMBExports.dll to ..\testR_TMBExports.dll: No such file or directory C:\rtools40\mingw64\bin\nm.exe: 'tmblib': No such file`

In the `./src/TMB/` folder there is no `testR_TMBExports.dll` file (hence the warning above) after the supposed compilation. My R package is called `testR`.

**Comment by jmhatch** [comment]
After some digging around, this may be related to `TMB`, so not a `TMBtools` issue.

**Comment by jmhatch** [comment]
I thought this might be a `TMB` issue, but the model compiles using `TMB::compile`.  As a quick test, I replaced the `NormalNLL.hpp` file in the example with, 
```
/// @file NormalNLL.hpp

#ifndef NormalNLL_hpp
#define NormalNLL_hpp

#undef TMB_OBJECTIVE_PTR
#define TMB_OBJECTIVE_PTR obj

/// Negative log-likelihood of the normal distribution.
template<class Type>
Type NormalNLL(objective_function<Type>* obj) {
  using namespace density;
  matrix<Type> Sigma(3,3);
  Sigma.fill(0.1);             // Fill the whole matrix
  Sigma.diagonal() *= 10.0;    // Multiply diagonal by 10 to positive definite Sigma
  vector<Type> x0(3);          // Point of evaluation
  x0.fill(0.0);                // Initialize x0 to be zero
  MVNORM_t<Type> N_0_Sigma(Sigma);   // N_0_Sigma is now a Distribution
  vector<Type> res(3);
  res = N_0_Sigma(x0);         // Evaluates (neg. log) density at x
  return res.sum();
}

#undef TMB_OBJECTIVE_PTR
#define TMB_OBJECTIVE_PTR this

#endif
```
I then tried to build the example, but it took a long time and did not produce a `*.dll` file (like above). Session info below,
```
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.1.0 tools_4.1.0 
```

Thanks for any help!

**Comment by mlysy** [comment]
I can't reproduce the error either on my local machine (OSX) or on CRAN [winbuilder](https://win-builder.r-project.org/) (Windows).

Can you please create a complete package repo out of your example above, i.e., with your `NormalNLL` modified to accept differentiable inputs and with corresponding files `R/norm_ADFun.R` and `tests/testthat/test-norm_ADFun.R`?  I would like to check that the compiled code does what it's supposed to...

**Comment by jmhatch** [comment]
Sure! I will try to put something together in the next day or so. 

Ok, I put together a repo called [testR](https://github.com/jmhatch/testR) and added you as a collaborator (or feel free to fork the repo). When I tried `pkgbuild::compile_dll()` it took a long time (hours) and then failed. So I wasn't able to vet the repo thoroughly, or at all really. But I tried to mimic the examples in `TMBtools` and included the files you asked for, so hopefully it'll work :crossed_fingers:.

**Comment by jmhatch** [comment]
Still having issues compiling an R pkg w/ TMB code using TMBtools when the {density} namespace is being used. I now get the following errors:
> Fatal error: can't write 315 bytes to section .text of testR_TMBExports.o: 'file too big'
> Fatal error: testR_TMBExports.o: file too big

I upgraded my Rtools, so I wanted to give this another try.

**Comment by mlysy** [comment]
Can also you please try compiling on CRAN [winbuilder](https://win-builder.r-project.org/)?

**Comment by jmhatch** [comment]
Just tried on winbuilder and I think it compiled. Must be an issue with my laptop. Sorry and thanks for the help.

> * installing *source* package 'testR' ...
> ** using staged installation
> ** libs
> g++ -std=gnu++11  -I"D:/RCompile/recent/R-4.2.2/include" -DNDEBUG  -I'D:/RCompile/CRANpkg/lib/4.2/TMB/include' -I'D:/RCompile/CRANpkg/lib/4.2/MASS/include' -I'D:/RCompile/CRANpkg/lib/4.2/emdbook/include'   -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"     -pedantic -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c init_dummy_file.cpp -o init_dummy_file.o
> (cd TMB; D:/RCompile/recent/R-4.2.2/bin/x64/Rscript \
> --no-save --no-restore compile.R '')
> make[1]: Entering directory '/d/temp/RtmpKUiwr5/R.INSTALL2d9e85f2430bf/testR/src/TMB'
> g++ -std=gnu++11  -I"D:/RCompile/recent/R-4.2.2/include" -DNDEBUG -I"D:/RCompile/CRANpkg/lib/4.2/TMB/include" -I"D:/RCompile/CRANpkg/lib/4.2/RcppEigen/include"   -DTMB_EIGEN_DISABLE_WARNINGS   -DTMB_LIB_INIT=R_init_testR_TMBExports  -DCPPAD_FRAMEWORK -I'D:/RCompile/CRANpkg/lib/4.2/TMB/include' -I'D:/RCompile/CRANpkg/lib/4.2/MASS/include' -I'D:/RCompile/CRANpkg/lib/4.2/emdbook/include'   -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"     -pedantic -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c testR_TMBExports.cpp -o testR_TMBExports.o
> g++ -std=gnu++11 -shared -s -static-libgcc -o testR_TMBExports.dll tmp.def testR_TMBExports.o -Ld:/rtools42/x86_64-w64-mingw32.static.posix/lib/x64 -Ld:/rtools42/x86_64-w64-mingw32.static.posix/lib -LD:/RCompile/recent/R-4.2.2/bin/x64 -lR
> make[1]: Leaving directory '/d/temp/RtmpKUiwr5/R.INSTALL2d9e85f2430bf/testR/src/TMB'
> make[1]: Entering directory '/d/temp/RtmpKUiwr5/R.INSTALL2d9e85f2430bf/testR/src/TMB'
> make[1]: Leaving directory '/d/temp/RtmpKUiwr5/R.INSTALL2d9e85f2430bf/testR/src/TMB'
> [1] TRUE
> D:\rtools42\x86_64-w64-mingw32.static.posix\bin\nm.exe: 'tmblib': No such file
> g++ -std=gnu++11 -shared -s -static-libgcc -o testR.dll tmp.def init_dummy_file.o -Ld:/rtools42/x86_64-w64-mingw32.static.posix/lib/x64 -Ld:/rtools42/x86_64-w64-mingw32.static.posix/lib -LD:/RCompile/recent/R-4.2.2/bin/x64 -lR
> installing to d:/RCompile/CRANguest/R-release/lib/00LOCK-testR/00new/testR/libs/x64
> ** R
> ** byte-compile and prepare package for lazy loading
> ** help
> No man pages found in package  'testR' 
> *** installing help indices
> ** building package indices
> ** testing if installed package can be loaded from temporary location
> ** testing if installed package can be loaded from final location
> ** testing if installed package keeps a record of temporary installation path
> * MD5 sums
> packaged installation of 'testR' as testR_0.0.0.9000.zip
> * DONE (testR)
