### ISSUE TITLE
Error in getDLLRegisteredRoutines.DLLInfo(dll, addNames = FALSE)

### ISSUE THREAD

**Issue by krpaulson** [mlysy/RcppTMBTest#8]
Hello,

Thank you for this helpful package! I've added TMB to an existing package following these instructions, and now I am getting the following error:

```
> pkgbuild::compile_dll()
> devtools::document()
ℹ Updating mypackage documentation
ℹ Loading mypackage
Error in getDLLRegisteredRoutines.DLLInfo(dll, addNames = FALSE) : 
  must specify DLL via a “DLLInfo” object. See getLoadedDLLs()
```

Do you know how to troubleshoot this?

Thanks again,
Katie

**Comment by mlysy** [comment]
Hi Katie,

Here's what I might try:

- See if you can (i) run the package unit tests and (ii) create a test package from scratch using the README instructions.  This would be my "sanity check" that I've at least installed the package correctly.

- Try quitting + restarting R liberally between C++ compiles (I might try it the full way, not the automatic R Studio way that reloads the previous workspace for you).  R really struggles to load/unload updated DLLs correctly.  In particular, I think `devtools::document()` may be trying to run the TMB code for you, which I've personally found to be super unreliable without a quit + restart after compiling.

- Try running `getLoadedDLLs()` you should see something containing `mypackage_TMBExports` in that list...

- If I could get the package creation instructions from the README to work, then as a last resort I would move your existing package file by file into that newly created package, intermittently checking that the package is compiling/installing as expected.

**Comment by krpaulson** [comment]
Thank you! This is helpful, and some combination of the above resolved my issue.
